// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import { buildActiveDrRunQuery, buildChangedPlanPayload, findActiveDrRun, requiresSourceHardwareRefresh, resolveDrSourceDiskFormat, resolveDrSourceDiskType, resolveTargetComputeSizingValue, targetComputeFields, invalidTargetComputeField, updateAutoGeneratedDiskNames } from '@/utils/dr/planForm'

describe('DR source disk storage contract', () => {
  it('keeps SharedMountPoint KVM volumes on the file/qcow2 path', () => {
    const details = { storagePoolType: 'SharedMountPoint', format: 'qcow2' }
    expect(resolveDrSourceDiskType(details, '/mnt/glue-gfs/volume-uuid')).toBe('file')
    expect(resolveDrSourceDiskFormat(details, '/mnt/glue-gfs/volume-uuid', true)).toBe('qcow2')
  })

  it('does not rewrite RBD or VMware file formats', () => {
    expect(resolveDrSourceDiskType({ storagePoolType: 'RBD' }, 'rbd:rbd/image')).toBe('rbd')
    expect(resolveDrSourceDiskFormat({ storagePoolType: 'RBD' }, 'rbd:rbd/image', true)).toBe('raw')
    expect(resolveDrSourceDiskFormat({}, '[ds] vm/disk.vmdk', false)).toBe('')
  })
})

describe('DR plan form compute sizing', () => {
  it('preserves persisted edit sizing when inventory is incomplete', () => {
    expect(resolveTargetComputeSizingValue(undefined, 2100, true)).toBe(2100)
  })

  it('preserves user sizing after source inventory refresh', () => {
    expect(resolveTargetComputeSizingValue(2400, 2100, true)).toBe(2100)
  })

  it('does not preserve stale sizing after an explicit selection change', () => {
    expect(resolveTargetComputeSizingValue(undefined, 2100, false)).toBeUndefined()
  })

  it('submits only fields changed after the edit form was initialized', () => {
    const baseline = {
      name: 'Windows DR',
      description: 'before',
      guidedplan: true,
      targetcpuspeed: 2100,
      diskmappingsjson: '[{"sourceDiskId":"2000"}]'
    }
    const current = Object.assign({}, baseline, { description: 'after' })

    expect(buildChangedPlanPayload(current, baseline)).toEqual({ description: 'after' })
  })

  it('keeps an explicitly changed protected placement field in the update payload', () => {
    expect(buildChangedPlanPayload(
      { description: 'same', targetcomputeref: 'offering-2' },
      { description: 'same', targetcomputeref: 'offering-1' }
    )).toEqual({ targetcomputeref: 'offering-2' })
  })

  it('refreshes an existing remote KVM mapping with incomplete source hardware', () => {
    expect(requiresSourceHardwareRefresh({
      direction: 'KVM_TO_KVM',
      mappingjson: JSON.stringify({
        source: {
          hardware: {
            errorCode: 'SOURCE_HARDWARE_INVENTORY_REQUIRED'
          }
        }
      })
    })).toBe(true)
    expect(requiresSourceHardwareRefresh({
      direction: 'ABLESTACK_TO_ABLESTACK',
      mappingjson: JSON.stringify({
        direction: 'KVM_TO_KVM',
        source: {
          hardware: {
            errorCode: 'SOURCE_HARDWARE_INVENTORY_REQUIRED'
          }
        }
      })
    })).toBe(true)
  })

  it('refreshes an existing SharedMountPoint mapping with an incomplete source storage contract', () => {
    const plan = {
      direction: 'KVM_TO_KVM',
      mappingjson: JSON.stringify({
        source: { hardware: { sourceHostUuid: 'host-uuid' } },
        disks: [{
          source: { path: '/mnt/glue-gfs/volume-uuid' },
          target: { type: 'file', format: 'qcow2' }
        }]
      })
    }
    expect(requiresSourceHardwareRefresh(plan)).toBe(true)
    expect(requiresSourceHardwareRefresh(plan, { targetcomputeref: 'offering-2' })).toBe(true)
    expect(requiresSourceHardwareRefresh(plan, { description: 'metadata only' })).toBe(false)
    expect(requiresSourceHardwareRefresh(plan, { rposeconds: 600 })).toBe(false)
  })

  it('keeps normal and VMware edit payloads on the changed-field path', () => {
    expect(requiresSourceHardwareRefresh({
      direction: 'KVM_TO_KVM',
      mappingjson: JSON.stringify({ source: { hardware: { sourceHostUuid: 'host-uuid' } } })
    })).toBe(false)
    expect(requiresSourceHardwareRefresh({
      direction: 'KVM_TO_KVM',
      mappingjson: JSON.stringify({
        source: { hardware: { firmware: 'UEFI' } },
        disks: [{
          source: { path: '/mnt/glue-gfs/volume-uuid', type: 'file', format: 'qcow2' }
        }]
      })
    })).toBe(false)
    expect(requiresSourceHardwareRefresh({
      direction: 'VMWARE_TO_KVM',
      mappingjson: '{}'
    })).toBe(false)
  })

  it('renames only automatically generated target disk names with the target VM', () => {
    expect(updateAutoGeneratedDiskNames([
      { targetDiskName: 'old-target-disk-0' },
      { targetDiskName: 'operator-disk' }
    ], 'old-target', 'new-target')).toEqual([
      { targetDiskName: 'new-target-disk-0' },
      { targetDiskName: 'operator-disk' }
    ])
  })

  it('selects only an active run with a stable API id', () => {
    const runs = [
      { id: 'completed-id', state: 'SUCCEEDED' },
      { state: 'RUNNING' },
      { id: 'active-id', state: 'RUNNING' }
    ]
    expect(findActiveDrRun(runs, run => run.state === 'RUNNING')).toEqual(runs[2])
    expect(findActiveDrRun(runs, run => run.state === 'WAITING')).toBeNull()
  })

  it('pairs the active-run page size with an explicit first page', () => {
    expect(buildActiveDrRunQuery('plan-id')).toEqual({
      planid: 'plan-id',
      page: 1,
      pagesize: 20
    })
  })
})

describe('DR target offering fields', () => {
  it('locks only fixed fields on partially dynamic offerings', () => {
    const fields = targetComputeFields({ cpu: '4', speed: '2000', minmemory: '1024', maxmemory: '8192' })
    expect(fields.map(field => !!field.fixed)).toEqual([true, true, false])
    expect(invalidTargetComputeField(fields, { targetmemory: 512 }).key).toBe('targetmemory')
    expect(invalidTargetComputeField(fields, { targetmemory: 8192 })).toBeUndefined()
    expect(invalidTargetComputeField(fields, { targetmemory: 8193 }).key).toBe('targetmemory')
  })
  it('requires missing speed explicitly and rejects fractional or nonpositive values', () => {
    const fields = targetComputeFields({ mincpunumber: '1', maxcpunumber: '64' })
    const form = { targetcpunumber: 2, targetmemory: 1024 }
    expect(invalidTargetComputeField(fields, form).key).toBe('targetcpuspeed')
    form.targetcpuspeed = 2000
    expect(invalidTargetComputeField(fields, form)).toBeUndefined()
    for (const value of [0, -1, 1.5, NaN, 65]) {
      expect(invalidTargetComputeField(fields, { ...form, targetcpunumber: value }).key).toBe('targetcpunumber')
    }
  })
  it('fixed offering replacement discards previously entered dynamic sizing', () => {
    expect(resolveTargetComputeSizingValue(4, 16, false)).toBe(4)
    expect(resolveTargetComputeSizingValue(undefined, 2000, false)).toBeUndefined()
  })
})
